// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7InU9NKZZ--tdMBxhva2jQvzNfdwXNjI',
    appId: '1:784175758166:web:e35317a1abbfe2db7974f7',
    messagingSenderId: '784175758166',
    projectId: 'mahad-food-delivery',
    authDomain: 'mahad-food-delivery.firebaseapp.com',
    storageBucket: 'mahad-food-delivery.firebasestorage.app',
    measurementId: 'G-EJNJFQ49LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ0cN5rF4NpNXj9efUMZHNiIgfubBHxME',
    appId: '1:784175758166:android:ecaaf6a74ffe88557974f7',
    messagingSenderId: '784175758166',
    projectId: 'mahad-food-delivery',
    storageBucket: 'mahad-food-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxAKyrUGbCGgd3Se0GwX-HMLFO3v0k0tM',
    appId: '1:784175758166:ios:c374ea0b4c99a69b7974f7',
    messagingSenderId: '784175758166',
    projectId: 'mahad-food-delivery',
    storageBucket: 'mahad-food-delivery.firebasestorage.app',
    iosBundleId: 'com.restaurant.foodDeliveryApp',
  );

}